<p>exception works!</p>
<h2>Output (catchError)</h2>
<div>RESPONSE: {{ responseCatchError }}</div>
<h2>Output (throw)</h2>
<div>RESPONSE: {{ responseThrowError }}</div>
